version: "3.3"
services:
  allocation:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_DB=$REDIS_DB
      - DB_TYPE=$DB_TYPE
      - SQLALCHEMY_DATABASE_URI=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@database:$DB_PORT/postgres
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
      - "database"
  redis:
    image: "redis:alpine"
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "5432:5432"
