version: "3.3"
services:
  allocation:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_PATH=prod.db
      - DB_TYPE=SQLite3
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
  redis:
    image: "redis:alpine"
