version: "3.3"
services:
  allocation:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_PATH=prod.db
      - DB_TYPE=SQLITE
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
  redis:
    image: "redis:alpine"
