"""Implement discarded option

Revision ID: c9e92a43c086
Revises: 30fc7cb4bf53
Create Date: 2022-01-30 12:25:59.163281

"""
from alembic import op
import sqlalchemy as sa
import allocation.interfaces.database.datatypes


# revision identifiers, used by Alembic.
revision = "c9e92a43c086"
down_revision = "30fc7cb4bf53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("batches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("discarded", sa.Boolean(), nullable=True))

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("discarded", sa.Boolean(), nullable=True))

    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("discarded", sa.Boolean(), nullable=True))

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("discarded", sa.Boolean(), nullable=True))

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("discarded", sa.Boolean(), nullable=True))

    with op.batch_alter_table("skus", schema=None) as batch_op:
        batch_op.add_column(sa.Column("discarded", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skus", schema=None) as batch_op:
        batch_op.drop_column("discarded")

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("discarded")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("discarded")

    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_column("discarded")

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_column("discarded")

    with op.batch_alter_table("batches", schema=None) as batch_op:
        batch_op.drop_column("discarded")

    # ### end Alembic commands ###
